### ISSUE TITLE
Incorrect Paths to assets  - css and js

### ISSUE THREAD

**Issue by webkingashu** [acacha/adminlte-laravel#3] opened 2015-06-02 03:13 UTC
Hi, 
As described, after installing this package, it does not load the css and js files correctly, instead console in chrome gives errors - 

`Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/css/AdminLTE.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhos`

As you can see, it is loading trying to get the assets from localhost/css  which isn't the valid location

Instead it should access the files from localhost/myapppname/public/ directory right??

Please help

**Comment by acacha** [comment] 2015-06-03 16:34
I suppose the problem is about using (Apache) aliases http://localhost/myapp instead of virtualHost with a custom domain or subdomain: http://myapp.mydomain.com.

Are you using Homestead (http://laravel.com/docs/5.0/homestead)? Homestead uses Nginx and configure virtual hosts by default and I recommend you the use of Homestead with Laravel development.

You can also use Apache but needs additional steps like pretty urls configuration: http://laravel.com/docs/5.0

Anyway I'll check the code and submit a new commit trying to avoid this error when using aliases. Please stay tunned ;-)

**Comment by acacha** [comment] 2015-06-03 16:44
Version 0.1.1 released with this bug resolved adding assets function.

**Comment by acacha** [comment] 2015-06-03 16:45
Remember to update package with $ composer update!!

**Comment by webkingashu** [comment] 2015-06-04 06:49
Yup, 
I did the fix myself by using `{{asset('path/to/asset/files')}}` in partial blade files.

You are correct, the issue is on localhost, I am on XAMPP (windows) since i did not created custom virtual host.  However using `{{asset('path')}}` location seems to work everywhere -)

Thank you for the same anyway

**Comment by acacha** [comment] 2015-06-04 09:21
You are welcome!

**Closed by acacha** 2015-06-04 09:21 UTC

**Comment by haqnawazwgbm** [comment] 2017-06-20 07:13
Hi,
i have download the laravel project but it's css is not loading on my localhost. Please anyone know help me.
