### ISSUE TITLE
Route [frontend.auth.account.confirm.resend] not defined

### ISSUE THREAD

**Issue by fricna** [acacha/adminlte-laravel#304] opened 2017-08-26 20:05 UTC
Followed the installation instructions for Laravel and the welcome page loads but if I try to do anything else I get the following error. Can someone help me out?
`Route [frontend.auth.account.confirm.resend] not defined. (View: /home/victor/adminlte/resources/views/vendor/adminlte/layouts/partials/htmlheader.blade.php) (View: /home/victor/adminlte/resources/views/vendor/adminlte/layouts/partials/htmlheader.blade.php) (View: /home/victor/adminlte/resources/views/vendor/adminlte/layouts/partials/htmlheader.blade.php)
--`

**Comment by acacha** [comment] 2017-08-31 14:40
Umm @fricna are you sure are you speaking about this package? I'm not aware of any frontend.auth.account.confirm.resend ?

I will close this issue feel because I cannot reproduce the problem. Please feel free to ask me to reopen the issue if you can give me more information.

**Closed by acacha** 2017-08-31 14:40 UTC
