### ISSUE TITLE
Error when run “adminlte-laravel install”

### ISSUE THREAD

**Issue by JKChen** [acacha/adminlte-laravel#291] opened 2017-07-07 09:56 UTC
![image](https://user-images.githubusercontent.com/7858123/27952809-2d5be7fc-633c-11e7-8446-e11418a43846.png)

And I found that a wrong path of adminlte-laravel provider has been added maybe by `llum` in `config/app.php` file.
![image](https://user-images.githubusercontent.com/7858123/27952852-5c0ccdf0-633c-11e7-8831-c1fb2d3bb31b.png)

**Comment by JKChen** [comment] 2017-07-10 07:50
Sorry, my fault. Just run `composer require "acacha/admin-lte-template-laravel:4.*"` instead can fix the fake error above, because my laravel is 5.4.

**Comment by acacha** [comment] 2017-08-30 15:57
I don't know the reason all \ are skipped in your config/app.php file... I will try to reproduce that but if nobody else have the problem I will close the issue. Thanks for you cooperation!

**Closed** 2017-08-31 15:54 UTC
Labels: help wanted
