### ISSUE TITLE
 Problem during installation

### ISSUE THREAD

**Issue by marioser** [acacha/adminlte-laravel#324] opened 2017-09-17 03:16 UTC
I am very new using php and laravel, now adminLTE, which I see is a great template. However I got the following error during the installation. view image. 

<a href="https://ibb.co/kBE94Q"><img src="https://preview.ibb.co/e9atW5/Captura_de_pantalla_2017_09_16_a_la_s_9_53_23_a_m.png" alt="Captura_de_pantalla_2017_09_16_a_la_s_9_53_23_a_m" border="0"></a><br /><a target='_blank' href='https://es.imgbb.com/'>fotos para web gratis</a><br />

However I continued as if I had not had this error and applied the recommended steps for installation in Laravel 5.4 (Manual Installation) using composer.

but when use a test using the register button does not execute anything and the mouse is left with a symbol of not allowed or something like that. The icons for username and password doesn't work

<a href="https://ibb.co/fwxU4Q"><img src="https://preview.ibb.co/gTY2PQ/Captura_de_pantalla_2017_09_16_a_la_s_10_16_33_a_m.png" alt="Captura_de_pantalla_2017_09_16_a_la_s_10_16_33_a_m" border="0"></a><br /><a target='_blank' href='https://es.imgbb.com/'>fotos para web gratis</a><br />
I registered the provider and the aliases

I use MAMP 5 and PHP 7.0.1
MAC Os Sierra 10.12.6
Navegator testing Chrome & Safari

**Comment by acacha** [comment] 2017-10-14 08:41
Sorry I does not give support for Windows using MAMP (I'm not using Windows). Maybe someone else could help you but I think the problem is related with not habinv unzip command in you environment. 

I close this issue because I think is related with environment not a package problem.

**Closed by acacha** 2017-10-14 08:41 UTC
