### ISSUE TITLE
make:mvc name fail

### ISSUE THREAD

**Issue by plguerra** [acacha/adminlte-laravel#255] opened 2017-04-24 13:59 UTC
php artisan make:mvc names
Model created successfully
Created Migration: 2017_04_24_134546_create names_table
Runing command php artisan make:route names --type=controller --method=get -a --menu

[Acacha\Filesystem\FileDoesNotExists]
File does not exixts

* Operating system and version Windows 7

**Comment by slpi1** [comment] 2017-05-09 08:14
for the reason of  method`getPath` in `Acacha\Filesystem\Filesystem` con't work well.it return a path like `//E:\www\...`

**Comment by acacha** [comment] 2017-05-23 06:23
Ok it seems then like a duplicate of https://github.com/acacha/adminlte-laravel/issues/267

**Closed by acacha** 2017-05-23 06:23 UTC

**Comment by otipip90** [comment] 2017-05-27 18:07
Then someone already has a truly proven answer to this problem
 $ php artisan make: view about
File does not exist
I just do not want to alter the code without knowing, I've been a week with this problem and I have not been able to solve it
